general:
  name: 19.2_single_tcr
  description: 19.2_pretrain_finetune_esm

data:
  data_path: /home/hughy/tcr2epi/data/clean_data/no_round1_filter/AS19.2_neg=rnd234c0_pos=rnd4c5.csv
  batch_size: 8

model:
  pretrained_weights: "/home/hughy/DL4TCR/model_outputs/vdjdb_pretrain/lightning_logs/finetune_esm/checkpoints/epoch=8-step=31653.ckpt"
  use_pos_weight: true
  encoder_dim: 1280
  use_attn: false
  freeze_encoder: false
  esm_weights: /opt/gpudata/hughy/esm/esm2_t33_650M_UR50D.pt
  patience: 10
  lr: 1.e-6
  weight_decay: 1.e-6
  epochs: 1000
  seed: 1
  precision: bf16
  gpu_devices: 2
  device_num: [0,1]
  strategy: ddp
  tb_logger_path: weights/
  tb_logger_folder: single_tcr/
  version_name: 19.2_finetune_esm